spring:
  datasource:
    url: jdbc:h2:mem:testes
    driverClassName: org.h2.Driver
    username: admin
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true

server:
 port: 9090

